### ISSUE TITLE
How to use this with youtube-dl

### ISSUE THREAD

**Issue by pratikbalar** [reiz/nginx_proxy#12]
getting this `400` when set proxy with `youtube-dl` 
```bash
$ youtube-dl --proxy http://nginx_proxy:8888 -icwf best 'https://www.youtube.com/watch?v=Wk1oClYJE58' 
[youtube] Wk1oClYJE58: Downloading webpage
WARNING: Unable to download webpage: <urlopen error Tunnel connection failed: 400 Bad Request>
[youtube] Wk1oClYJE58: Downloading API JSON
ERROR: Unable to download API page: <urlopen error Tunnel connection failed: 400 Bad Request> (caused by URLError(OSError('Tunnel connection failed: 400 Bad Request')))
```
getting this in `/var/log/nginx_errors.log`
```
2021/08/31 17:53:23 [error] 7#7: *156 proxy_connect: connection error while connecting to upstream, client: 172.17.0.1, server: ~.+, request: "CONNECT firebaseinstallations.googleapis.com:443 HTTP/1.1", host: "firebaseinstallations.googleapis.com:443"
2021/08/31 17:53:23 [crit] 7#7: *167 connect() to [2607:f8b0:4003:c05::5f]:443 failed (99: Cannot assign requested address) while connecting to upstream, client: 172.17.0.1, server: ~.+, request: "CONNECT firebaseinstallations.googleapis.com:443 HTTP/1.1", host: "firebaseinstallations.googleapis.com:443"
```

I'm running this proxy with gluetun VPN, I'm sure that VPN is running properly.
```yaml
version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888 # Built-in HTTP control server
    volumes:
      - ./vpn:/gluetun
    environment:
      - VPNSP=nordvpn
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - TZ=Asia/Kolkata
  nginx:
    network_mode: "container:gluetun"
    restart: always
    image: reiz/nginx_proxy
    container_name: forward
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
    environment:
      - TZ=Asia/Kolkata
```
